# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = false
format = """$username$hostname$directory $character"""

# move the rest of the prompt to the right
right_format = """$git_branch$git_state$git_status $git_metrics$status( $cmd_duration) $time"""

[directory]
style = "fg:#FC4DFF"
format = "[$path]($style)"
truncation_length = 3
truncate_to_repo = false
fish_style_pwd_dir_length = 1
# truncation_symbol = "…/"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

# This is very laggy for some reason
[git_status]
ahead = '[⇡${count} ](yellow)'
diverged = '[⇕ ⇡${ahead_count} ⇣${behind_count} ](yellow)'
behind = '[⇣${count} ](yellow)'
staged = '[ ${count} ](green)'
deleted = '[ ${count} ](green)'
renamed = '[󰗧${count} ](green)'
modified = '[ ${count} ](red)'
untracked = '[?${count} ](red)'
stashed = ''
format = '(\[ $all_status$ahead_behind\])'
# disabled = true

[git_metrics]
disabled = true
added_style = 'bold blue'
format = '[+$added]($added_style)/[-$deleted]($deleted_style) '

[git_branch]
# format = '[$symbol$branch(:$remote_branch)]($style)'
format = '[$symbol$branch(staged)]($style)'


[time]
disabled = false
format = '[$time]($style)'
time_format = '%R'

[cmd_duration]
min_time = 50
format = '[$duration](bold green)'
# show_milliseconds = true
